// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FunShare_Admin.Models
{
    public partial class AdvertiseProduct
    {
        public AdvertiseProduct()
        {
            AdvertiseOrder = new HashSet<AdvertiseOrder>();
            AdvertiseProductDetail = new HashSet<AdvertiseProductDetail>();
        }

        public int PackageId { get; set; }
        public string PackageName { get; set; }
        public string AdsDescription { get; set; }

        public virtual ICollection<AdvertiseOrder> AdvertiseOrder { get; set; }
        public virtual ICollection<AdvertiseProductDetail> AdvertiseProductDetail { get; set; }
    }
}