// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FunShare_Admin.Models
{
    public partial class CouponList
    {
        public CouponList()
        {
            MemberCoupon = new HashSet<MemberCoupon>();
            Order = new HashSet<Order>();
        }

        public int CouponId { get; set; }
        public string Name { get; set; }
        public decimal? Discount { get; set; }
        public string Description { get; set; }
        public int? ProductId { get; set; }
        public DateTime? DueDate { get; set; }

        public virtual Product Product { get; set; }
        public virtual ICollection<MemberCoupon> MemberCoupon { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}