// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FunShare_Admin.Models
{
    public partial class District
    {
        public District()
        {
            CustomerInfomation = new HashSet<CustomerInfomation>();
            ProductDetail = new HashSet<ProductDetail>();
        }

        public int DistrictId { get; set; }
        public string DistrictName { get; set; }
        public int CityId { get; set; }

        public virtual City City { get; set; }
        public virtual ICollection<CustomerInfomation> CustomerInfomation { get; set; }
        public virtual ICollection<ProductDetail> ProductDetail { get; set; }
    }
}