// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FunShare_Admin.Models
{
    public partial class Region
    {
        public Region()
        {
            City = new HashSet<City>();
        }

        public int RegionId { get; set; }
        public string RegionName { get; set; }

        public virtual ICollection<City> City { get; set; }
    }
}