// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FunShare_Admin.Models
{
    public partial class Status
    {
        public Status()
        {
            CustomerInfomation = new HashSet<CustomerInfomation>();
            Order = new HashSet<Order>();
            OrderDetail = new HashSet<OrderDetail>();
            Product = new HashSet<Product>();
            ProductDetail = new HashSet<ProductDetail>();
            Supplier = new HashSet<Supplier>();
        }

        public int StatusId { get; set; }
        public string Description { get; set; }
        public string StatusType { get; set; }

        public virtual ICollection<CustomerInfomation> CustomerInfomation { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        public virtual ICollection<Product> Product { get; set; }
        public virtual ICollection<ProductDetail> ProductDetail { get; set; }
        public virtual ICollection<Supplier> Supplier { get; set; }
    }
}