// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjFunShare_Core.ViewModels;

public partial class CMemberCouponViewModel
{
    public int MemberCouponId { get; set; }

    public int? CouponId { get; set; }

    public int? MemberId { get; set; }

    public int? StatusId { get; set; }

    public string CouponName { get; set; }  
    public string CouponDescription { get; set; }
    public decimal CouponDiscount { get; set; }

}