// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjFunShare_backend.Models;

public partial class Achievement
{
    public int AchievementId { get; set; }

    public string AchievementName { get; set; }

    public string AchievementDescription { get; set; }

    public string AchievementFileName { get; set; }

    public virtual ICollection<AchievementList> AchievementList { get; set; } = new List<AchievementList>();

    public virtual ICollection<MemberAchievement> MemberAchievement { get; set; } = new List<MemberAchievement>();
}