// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjFunShare_backend.Models;

public partial class Chat
{
    public int ChatMessengerId { get; set; }

    public int ReceiverId { get; set; }

    public int SenderId { get; set; }

    public string MessageContent { get; set; }

    public DateTime? MessageCreateTime { get; set; }
}