// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjFunShare_backend.Models;

public partial class Message
{
    public int MessageId { get; set; }

    public int OrderId { get; set; }

    public int? CustomerServiceId { get; set; }

    public string MessageContent { get; set; }

    public DateTime? Datetime { get; set; }

    public virtual Order Order { get; set; }
}