// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjFunShare_backend.Models;

public partial class PocketList
{
    public int PocketlistId { get; set; }

    public int ProductId { get; set; }

    public int MemberId { get; set; }

    public virtual CustomerInfomation Member { get; set; }

    public virtual Product Product { get; set; }
}