// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjFunShare_backend.Models;

public partial class ProductCategories
{
    public int ProductCategoryId { get; set; }

    public int ProductId { get; set; }

    public int SubCategoryId { get; set; }

    public virtual Product Product { get; set; }

    public virtual SubCategory SubCategory { get; set; }
}