// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjFunShare_backend.Models;

public partial class Region
{
    public int RegionId { get; set; }

    public string RegionName { get; set; }

    public virtual ICollection<City> City { get; set; } = new List<City>();
}