// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjFunShare_backend.Models;

public partial class Supplier
{
    public int SupplierId { get; set; }

    public string TaxId { get; set; }

    public string SupplierName { get; set; }

    public string SupplierPhone { get; set; }

    public string Email { get; set; }

    public int? CityId { get; set; }

    public byte[] SupplierPhoto { get; set; }

    public string Fax { get; set; }

    public string Password { get; set; }

    public string ContactPerson { get; set; }

    public byte[] LogoImage { get; set; }

    public string Description { get; set; }

    public int StatusId { get; set; }

    public string Address { get; set; }

    public virtual ICollection<AdvertiseOrder> AdvertiseOrder { get; set; } = new List<AdvertiseOrder>();

    public virtual City City { get; set; }

    public virtual ICollection<Product> Product { get; set; } = new List<Product>();

    public virtual Status Status { get; set; }
}