// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjFunShare_Core.Models;

public partial class AchievementList
{
    public int AchievementListId { get; set; }

    public int ProductId { get; set; }

    public int AchievementId { get; set; }

    public virtual Achievement Achievement { get; set; }

    public virtual Product Product { get; set; }
}