// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjFunShare_Core.Models;

public partial class AdvertiseProduct
{
    public int PackageId { get; set; }

    public string PackageName { get; set; }

    public string AdsDescription { get; set; }

    public virtual ICollection<AdvertiseOrder> AdvertiseOrder { get; set; } = new List<AdvertiseOrder>();

    public virtual ICollection<AdvertiseProductDetail> AdvertiseProductDetail { get; set; } = new List<AdvertiseProductDetail>();
}