// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjFunShare_Core.Models;

public partial class Chat
{
    public int ChatMessengerId { get; set; }

    public string ChatRoomId { get; set; }

    public int CustomerId { get; set; }

    public int SupplierId { get; set; }

    public string MessageContent { get; set; }

    public DateTime? MessageCreateTime { get; set; }

    public bool? WhoSend { get; set; }

    public virtual CustomerInfomation Customer { get; set; }

    public virtual Supplier Supplier { get; set; }
}