// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjFunShare_Core.Models;

public partial class Interest
{
    public int InterestId { get; set; }

    public int SubCategoryId { get; set; }

    public int MemberId { get; set; }

    public virtual CustomerInfomation Member { get; set; }

    public virtual SubCategory SubCategory { get; set; }
}