// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjFunShare_Core.Models;

public partial class LoginLog
{
    public int LoginId { get; set; }

    public int? MemberId { get; set; }

    public DateTime? LoginTime { get; set; }

    public string Device { get; set; }
}