// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjFunShare_Core.Models;

public partial class SubCategory
{
    public int SubCategoryId { get; set; }

    public string SubCategoryName { get; set; }

    public string SubCategoryDescription { get; set; }

    public int CategoryId { get; set; }

    public string AbilityOne { get; set; }

    public string AbilityTwo { get; set; }

    public string AbilityThree { get; set; }

    public virtual Categories Category { get; set; }

    public virtual ICollection<Interest> Interest { get; set; } = new List<Interest>();

    public virtual ICollection<ProductCategories> ProductCategories { get; set; } = new List<ProductCategories>();
}